# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."netv" = {
    image = "localhost/netv";
    environment = {
      "NETV_HTTPS" = "";
      "NETV_PORT" = "8000";
    };
    volumes = [
      "/vault/netv/cache:/app/cache:rw"
    ];
    ports = [
      "8000:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=netv"
      "--network=netv_default"
    ];
  };
  systemd.services."podman-netv" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-netv_default.service"
    ];
    requires = [
      "podman-network-netv_default.service"
    ];
    partOf = [
      "podman-compose-netv-root.target"
    ];
    upheldBy = [
      "podman-network-netv_default.service"
    ];
    wantedBy = [
      "podman-compose-netv-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-netv_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f netv_default";
    };
    script = ''
      podman network inspect netv_default || podman network create netv_default
    '';
    partOf = [ "podman-compose-netv-root.target" ];
    wantedBy = [ "podman-compose-netv-root.target" ];
  };

  # Builds
  systemd.services."podman-build-netv" = {
    path = [ pkgs.podman pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /vault/netv
      podman build -t netv .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-netv-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
