# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };
  networking.firewall.allowedTCPPorts = [ 3000 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."nodecast-tv" = {
    image = "localhost/compose2nix/nodecast-tv";
    environment = {
      "NODE_ENV" = "production";
      "PORT" = "3000";
    };
    volumes = [
      "/vault/nodecast/data:/app/data:rw"
    ];
    ports = [
      "3000:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=nodecast-tv"
      "--network=nodecast-tv_default"
    ];
  };
  systemd.services."podman-nodecast-tv" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-nodecast-tv_default.service"
    ];
    requires = [
      "podman-network-nodecast-tv_default.service"
    ];
    partOf = [
      "podman-compose-nodecast-tv-root.target"
    ];
    upheldBy = [
      "podman-network-nodecast-tv_default.service"
    ];
    wantedBy = [
      "podman-compose-nodecast-tv-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-nodecast-tv_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f nodecast-tv_default";
    };
    script = ''
      podman network inspect nodecast-tv_default || podman network create nodecast-tv_default
    '';
    partOf = [ "podman-compose-nodecast-tv-root.target" ];
    wantedBy = [ "podman-compose-nodecast-tv-root.target" ];
  };

  # Builds
  systemd.services."podman-build-nodecast-tv" = {
    path = [
      pkgs.podman
      pkgs.git
    ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      podman build -t compose2nix/nodecast-tv https://github.com/technomancer702/nodecast-tv.git#main
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-nodecast-tv-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
