[pyprland]
plugins = ["expose", "scratchpads", "shift_monitors"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.btop]
animation = "fromBottom"
command = "kitty --class kitty btop"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = true

[scratchpads.bluetooth]
animation = "fromLeft"
command = "blueman-manager"
class = ".blueman-manager-wrapped"
size = "40% 90%"
unfocus = "hide"
lazy = true

